version: '3.7'
services:
  web:
    build: ./web
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      #- ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: ${APP_PATH_CONTAINER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mariadb
    container_name: maria-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  nginx:
    image: nginx:1.17-alpine
    container_name: staff-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ${APP_PATH_HOST}:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/